[package]
name = "mod-list-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap_derive = { version = "4.0.0-rc.1" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
